import React, { FC } from 'react'
import Head from 'next/head'
import HeaderNav from '../HeaderNav/HeaderNav'

import style from './MainContainer.module.scss'

const MainContainer: FC = ({ children }) => {
  return (
    <>
      <Head>
        <title>Shopka</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HeaderNav />

      <div className={style.container}>{children}</div>
    </>
  )
}

export default MainContainer
